version: "2"
services:

  mongo:
    image: mongo:latest
    container_name: dasbot_mongo
    restart: always
      
  dasbot:
    image: wetterkrank/dasbot:latest
    container_name: dasbot_app
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    env_file: .env
